use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :warn_for_multiple_pod_sources => false, :deterministic_uuids => false
platform :ios, '8.0'

target 'LollypopSDK_Example' do
  
  pod 'lollypop', '0.2.0'
  
  target 'LollypopSDK_Tests' do
    inherit! :search_paths
  end
end

pre_install do |installer|
  def installer.verify_no_static_framework_transitive_dependencies; end
end
